=== jajaaa/wp_xmlPresentation/presentation.dtd
<!ELEMENT presentation (info, slide*)> <!-- korenovy element prezentacie, obsahuje informacie o prezentacii a nejake slidy -->
<!ELEMENT info (title, author, date?, organisation?)> <!-- Informacie o prezentacii -->

<!ELEMENT title (#PCDATA)> <!-- Nazov prezentacie -->
<!ELEMENT date (#PCDATA)> <!-- Datum vytvorenia -->
<!ELEMENT author (name, surname, degree?)> <!-- Autor prezentacie -->
<!ELEMENT name (#PCDATA)> <!-- Krstne meno autora -->
<!ELEMENT surname (#PCDATA)> <!-- Priezvisko autora -->
<!ELEMENT degree (#PCDATA)> <!-- Titul autora -->

<!ELEMENT organisation (orgtitle, orgsubtitle?)> <!-- Element popisujuci organizaciu -->
<!ELEMENT orgtitle (#PCDATA)> <!-- Nazov organizacie -->
<!ELEMENT orgsubtitle (#PCDATA)> <!-- Presnejsi nazov organizacie (nazov pracoviska ai.) -->

<!ELEMENT slide (heading, content?)> <!-- Element popisujuci slide -->
<!ELEMENT heading (#PCDATA)> <!-- Hlavicka (nadpis) slidu -->
<!ELEMENT content (para|list|image)*> <!-- Obsah slajdu, moze byt zmiesany z roznych elementov -->
<!ELEMENT para (#PCDATA|ref)*> <!-- Odsek na slajde, moze obsahovat referencie -->
<!ELEMENT ref ANY> <!-- Referencia -->
<!ELEMENT list (item+)> <!-- Zoznam poloziek -->
<!ELEMENT item (#PCDATA)> <!-- Jedna polozka v zozname -->
<!ATTLIST list style (bullet|number) "bullet"> <!-- Atribut urcujuci typ zoznamu - cislovany, odrazkovy -->
<!ELEMENT image (#PCDATA)> <!-- Obrazok -->

=== jajaaa/wp_xmlPresentation/presentation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE presentation SYSTEM "presentation.dtd"> 


<presentation>
  <info>
    <title>
      Vyhodnocovanie používateľského zážitku analýzou pohľadu a emócií
    </title>
    <author>
      <name>Majka</name>
      <surname>Dragúňova</surname>
    </author>
    <date>12.5.2016</date>
    <organisation>
      <orgtitle>Slovenská technická univerzita</orgtitle>
      <orgsubtitle>Fakulta informatiky a informačných technológií</orgsubtitle>
    </organisation>
  </info>
  
  <slide>
    <heading>Návrh scenára experimentu</heading>
    <content>
      <para color="green">Pripravovaný experiment bude pozostávať z dvoch častí:</para>
      <list style="number">
        <item>Testy na vizuálne hľadanie</item>
        <item>Hľadanie elementov na webových stránkach</item>
      </list>
      <para>Účastníci experimentu budú automaticky rozdelení na dve skupiny:</para>
      <list style="bullet">
      <item>Verzia A: Testy na vizuálne hľadanie -> Webové stránky</item>
      <item>Verzia B: Webové stránky -> Testy na vizuálne hľadanie</item>
    </list>
    </content>
  </slide>

  <slide>
    <heading>Ukážka stimulov - štandardný test</heading>
    <content>
      <para>Stimuly obsiahnuté v štandardnom teste na vizuálne hľadanie:</para>
      <image align="right">obr/ukazka_standard.png</image>
      <para>Návrh testu podľa existujúcich riešení, napr. <ref>http://gocognitive.net</ref>.</para>
      <list style="bullet">
        <item>Počty elementov:6, 12, 18, 32</item>
        <item>Ovládanie: tlačidlami klávesnice</item>
        <item>Špecifiká:  Stimul je zobrazený až po stlačení tlačidla.</item>
      </list>
    </content>
  </slide>  
  
  <slide>
    <heading>Ukážka stimulov - test s ikonami</heading>
    <content>
      <para color="red">Väčšia zobrazovacia plocha = viac pozorovateľných fixácií</para>
      <list style="bullet">
        <item>Počty elementov: 32, 64</item>
        <item>Ovládanie: myšou</item>
        <item>Špecifiká: zabrazenie maskovaného stimulu, na kontrolu presnosti odpovede</item>
      </list>
      <image>obr/ukazka_ico.png</image>
    </content>
  </slide>

  <slide>
    <heading>Webové stránky</heading>
    <content>
      <list style="bullet">
        <item>15 rôznych webovových stránok</item>
        <item>Stránky s obsahom, ktorý by sa (pravdepodobne) nemal týkať participantov (študentov)</item>
        <item>Použitie screenshotov - okamžité zobrazenie rovnaké pre všetkých</item>
      </list>
      <para>Priebeh tesovania bude nasledovný:</para>
      <list style="number">
        <item>Zobrazenie cieľového elementu</item>
        <item>Zobrazenie webovej stránky, na ktorej je potrebné cieľový elelemnt nájsť</item>
        <item>Odpoveď na otázku, či už niekedy participant danú stránku navštívil.</item>
      </list>
    </content>
  </slide>

  <slide>
    <heading>Celkový priebeh experimentu</heading>
    <content>
      <para>Celkovo bude experiment pozostávať z nasledujúcich častí:</para>
      <image>obr/exp.png</image>
    </content>
  </slide>

  <slide>
    <heading>Zhrnutie a diskusia</heading>
    <content>
      <para>Nech sa páči, pýtajte sa...</para>
    </content>
  </slide>

  <slide>
    <heading>Ďakujem za pozornosť</heading>
  </slide>
</presentation>
